version: '3.8'

services:
    api:
        build:
            context: .
            dockerfile: ./api.dockerfile
        image: lifechart-api
        ports:
            - "7147:7147"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_HTTP_PORT=https://+:8777/
            - ASPNETCORE_URLS=http://+:7147/
        volumes:
            - ./LifeChartAPI:/src
        command:
            - dotnet LifeChartAPI.dll

    app:
        build:
            context: .
            dockerfile: ./app.dockerfile
        image: lifechart-app
        ports:
            - "7010:7010"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_HTTP_PORT=https://+:6777/
            - ASPNETCORE_URLS=http://+:7010/
        volumes:
            - ./LifeChart:/src
        command:
            - dotnet LifeChart.dll
