// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SpendingBehavior
{
    public partial class SpendingModel
    {
        /// <summary>
        /// model input class for SpendingModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Counter")]
            public float Counter { get; set; }

            [ColumnName(@"ThreeMonthsPrior")]
            public float ThreeMonthsPrior { get; set; }

            [ColumnName(@"TwoMonthsPrior")]
            public float TwoMonthsPrior { get; set; }

            [ColumnName(@"OneMonthPrior")]
            public float OneMonthPrior { get; set; }

            [ColumnName(@"ThisMonth")]
            public float ThisMonth { get; set; }

            [ColumnName(@"LimitThisMonth")]
            public float LimitThisMonth { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SpendingModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SpendingModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
